Repository CoalAI/raami-dashboard, pull requests merged in 2021-09, with the labels that each got.

#14 Projects settings and app templated
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  README.md
  dashboard/templates/base.html
  dashboard/urls.py
  dashboard/views.py
  install.sh
  manage.py
  raamiDashboard/settings.py
  raamiDashboard/urls.py
  requirements.txt
Labels: good first issue, 2

#17 Added docker file and created migration for superuser
  Dockerfile
  dashboard/migrations/0001_create_user.py
  requirements.txt
Labels: enhancement

#19 Feature/county state
  .gitignore
  dashboard/score_service/__init__.py
  dashboard/score_service/gcloud_bq.py
  dashboard/score_service/score_calc_utils.py
  dashboard/templates/dashboard/pages/calculate-score.html
  dashboard/views.py
Labels: enhancement

#18 Scorefunction
  .gitignore
  dashboard/score_calc_service/gcloud_bq.py
  dashboard/score_calc_service/score_calc_utils.py
Labels: 3

#22 Send email function added
  dashboard/score_calc_service/email.py
  dashboard/templates/base.html
  dashboard/templates/dashboard/nav.html
  dashboard/templates/user/login.html
  raamiDashboard/settings.py
  static/images/favicon_d.png
Labels: enhancement

#25 Feature/notification pop and tables
  dashboard/templates/base.html
  dashboard/templates/dashboard/pages/calculate-score.html
  dashboard/templates/dashboard/pages/files-available.html
  dashboard/views.py
  static/js/data-table.js
  static/vendors/DataTables/css/dataTables.bootstrap.css
  static/vendors/DataTables/css/dataTables.bootstrap.min.css
  static/vendors/DataTables/css/dataTables.bootstrap4.css
  static/vendors/DataTables/css/dataTables.bootstrap4.min.css
  static/vendors/DataTables/css/dataTables.bootstrap5.css
  static/vendors/DataTables/css/dataTables.bootstrap5.min.css
  static/vendors/DataTables/css/dataTables.bulma.css
  static/vendors/DataTables/css/dataTables.bulma.min.css
  static/vendors/DataTables/css/dataTables.dataTables.css
  static/vendors/DataTables/css/dataTables.dataTables.min.css
  static/vendors/DataTables/css/dataTables.foundation.css
  static/vendors/DataTables/css/dataTables.foundation.min.css
  static/vendors/DataTables/css/dataTables.jqueryui.css
  static/vendors/DataTables/css/dataTables.jqueryui.min.css
  static/vendors/DataTables/css/dataTables.semanticui.css
  static/vendors/DataTables/css/dataTables.semanticui.min.css
  static/vendors/DataTables/css/jquery.dataTables.css
  static/vendors/DataTables/css/jquery.dataTables.min.css
  static/vendors/DataTables/images/sort_asc.png
  static/vendors/DataTables/images/sort_asc_disabled.png
  static/vendors/DataTables/images/sort_both.png
  static/vendors/DataTables/images/sort_desc.png
  static/vendors/DataTables/images/sort_desc_disabled.png
  static/vendors/DataTables/js/dataTables.bootstrap.js
  static/vendors/DataTables/js/dataTables.bootstrap.min.js
  static/vendors/DataTables/js/dataTables.bootstrap4.js
  static/vendors/DataTables/js/dataTables.bootstrap4.min.js
  static/vendors/DataTables/js/dataTables.bootstrap5.js
  static/vendors/DataTables/js/dataTables.bootstrap5.min.js
  static/vendors/DataTables/js/dataTables.bulma.js
  static/vendors/DataTables/js/dataTables.bulma.min.js
  static/vendors/DataTables/js/dataTables.dataTables.js
  static/vendors/DataTables/js/dataTables.dataTables.min.js
  static/vendors/DataTables/js/dataTables.foundation.js
  static/vendors/DataTables/js/dataTables.foundation.min.js
  static/vendors/DataTables/js/dataTables.jqueryui.js
  static/vendors/DataTables/js/dataTables.jqueryui.min.js
  static/vendors/DataTables/js/dataTables.semanticui.js
  static/vendors/DataTables/js/dataTables.semanticui.min.js
  static/vendors/DataTables/js/jquery.dataTables.js
  static/vendors/DataTables/js/jquery.dataTables.min.js
Labels: enhancement
